owner: petebachant
name: climaatmos-opt
title: ClimaAtmos optimization
description: Attempting to speed up ClimaAtmos when run with CUDA.
git_repo_url: https://github.com/petebachant/climaatmos-opt
environments:
  main:
    kind: julia
    julia: "1.11"
    path: .calkit/envs/main/Project.toml
  clima:
    kind: slurm
    host: clima.gps.caltech.edu
  py:
    kind: uv
    path: .calkit/envs/py/pyproject.toml

pipeline:
  stages:
    nsys-baseline:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - --output=results/nsys/baseline
        - julia
        - --project=ClimaAtmos.jl/.buildkite
        - ClimaAtmos.jl/perf/benchmark_step.jl
        - --config_file=config/climaatmos_progedmf_1m.yml
      inputs:
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl/src
        - config/climaatmos_progedmf_1m.yml
        - ClimaAtmos.jl/perf/benchmark_step.jl
      outputs:
        - path: results/nsys/baseline.nsys-rep
          storage: dvc
        - path: results/nsys/baseline.sqlite
          storage: dvc
    nsys-mod:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - --output=results/nsys/mod
        - julia
        - --project=ClimaAtmos.jl-mod/.buildkite
        - ClimaAtmos.jl-mod/perf/benchmark_step.jl
        - --config_file=config/climaatmos_progedmf_1m.yml
      inputs:
        - ClimaAtmos.jl-mod/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl-mod/src
        - config/climaatmos_progedmf_1m.yml
        - ClimaAtmos.jl-mod/perf/benchmark_step.jl
      outputs:
        - path: results/nsys/mod.nsys-rep
          storage: dvc
        - path: results/nsys/mod.sqlite
          storage: dvc
    compare-kernels:
      kind: jupyter-notebook
      notebook_path: notebooks/compare-kernels.ipynb
      environment: py
      inputs:
        - results/nsys/baseline.sqlite
        - results/nsys/mod.sqlite
      html_storage: git
      executed_ipynb_storage: git
    # Atmos AMIP baseline
    amip-baseline:
      kind: sbatch
      environment: clima
      script_path: scripts/run-julia-script.sh
      args:
        - --project=ClimaAtmos.jl/.buildkite
        - scripts/run_progedmf_1m.jl
      sbatch_options:
        - --gpus=1
        - --time=120
      inputs:
        - config/climaatmos_progedmf_1m.yml
        - scripts/run_progedmf_1m.jl
        - ClimaAtmos.jl/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl/src
    # Atmos AMIP modified
    amip-mod:
      kind: sbatch # Could just be shell-script, and we infer from environment
      environment: clima
      script_path: scripts/run-julia-script.sh
      args:
        - --project=ClimaAtmos.jl-mod/.buildkite
        - scripts/run_progedmf_1m.jl
      sbatch_options: # Could just be slurm_options?
        - --gpus=1
        - --time=120
      inputs:
        - config/climaatmos_progedmf_1m.yml
        - scripts/run_progedmf_1m.jl
        - ClimaAtmos.jl-mod/.buildkite/Manifest-v1.11.toml
        - ClimaAtmos.jl-mod/src
    analyze-logs:
      kind: jupyter-notebook
      notebook_path: notebooks/analyze-logs.ipynb
      environment: py
      inputs:
        - from_stage_outputs: amip-baseline
        - from_stage_outputs: amip-mod
      outputs:
        - path: figures/sypd-time-series.png
          storage: git
      html_storage: git
      executed_ipynb_storage: git

notebooks:
  - path: notebooks/analyze-logs.ipynb
    title: Analyze logs
    description: Analyzes the logs from the AMIP baseline and modified runs
      to compare performance metrics and visualize any differences.
    stage: analyze-logs
  - path: notebooks/compare-kernels.ipynb
    title: Compare kernels
    description: Compares the CUDA kernels between the baseline and modified
      runs using the Nsight profiling results to identify any performance
      differences.
    stage: compare-kernels

figures:
  - path: figures/sypd-time-series.png
    title: SYPD time series
    description:
    stage: analyze-logs

showcase:
  - notebook: notebooks/analyze-logs.ipynb

derived_from:
  project: petebachant/clima-local-geometry
  git_repo_url: https://github.com/petebachant/clima-local-geometry
  git_rev: ece59fefe42359b1594c90bea4b59ad886d3f9b5
